# Generated by Django 5.1.5 on 2025-04-26 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='personal_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.personaltodoitem'),
        ),
        migrations.AddField(
            model_name='notification',
            name='reminder_type',
            field=models.CharField(choices=[('deadline', 'Deadline Reminder'), ('overdue', 'Overdue Task'), ('assigned', 'Task Assigned')], default='deadline', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.task'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='deadline', max_length=200),
            preserve_default=False,
        ),
    ]
